---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: moneytree-config
data:
  config.yaml: |-
    ---
    symbols:
    - BTC
    - USD
    coinbase:
    {{- if .Values.moneytree.coinbase.useSandbox }}
      # Sandbox URLs
      websocketURL:  wss://ws-feed-public.sandbox.pro.coinbase.com
      baseURL: https://api-public.sandbox.pro.coinbase.com
    {{- else }}
      # Live URLs
      websocketURL:  wss://ws-feed.pro.coinbase.com
      baseURL: https://api.pro.coinbase.com
    {{- end }}
      key: {{ .Values.moneytree.coinbase.key }}
      passphrase: {{ .Values.moneytree.coinbase.passphrase }}
      secret: {{ .Values.moneytree.coinbase.secret }}
      
    debug: {{ .Values.moneytree.enableDebugLogs }}

    disableFees: {{ .Values.moneytree.disableFees }}

    followtheleader:
      maxOpenOrders: {{ .Values.moneytree.maxOpenOrders }}
      reversalSpread: {{ .Values.moneytree.reversalSpread }}
      targetReturn: {{ .Values.moneytree.targetReturn }}
      cycleDelay: {{ .Values.moneytree.cycleDelay }}
      refreshDatabasePairs: {{ .Values.moneytree.refreshDatabasePairs }}

    orderpair:
      missPercentage: {{ .Values.moneytree.missPercentage }}

    moneytree:
      forceMakerOrders: {{ .Values.moneytree.forceMakerOrders}}

    postgres:
      host: {{ .Release.Name }}-postgresql
      password: {{ .Values.moneytree.postgresql.password }}
      database: {{ .Values.moneytree.postgresql.database }}