{{- if .Values.moneytree.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "moneytree.serviceAccountName" . }}
  labels:
    {{- include "moneytree.labels" . | nindent 4 }}
  {{- with .Values.moneytree.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
