// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MoneytreeClient is the client API for Moneytree service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoneytreeClient interface {
	// Places an order pair in the system using the current price as the starting point.
	PlacePair(ctx context.Context, in *PlacePairRequest, opts ...grpc.CallOption) (*PlacePairResponse, error)
	GetOpenOrders(ctx context.Context, in *NullRequest, opts ...grpc.CallOption) (*PairCollection, error)
}

type moneytreeClient struct {
	cc grpc.ClientConnInterface
}

func NewMoneytreeClient(cc grpc.ClientConnInterface) MoneytreeClient {
	return &moneytreeClient{cc}
}

func (c *moneytreeClient) PlacePair(ctx context.Context, in *PlacePairRequest, opts ...grpc.CallOption) (*PlacePairResponse, error) {
	out := new(PlacePairResponse)
	err := c.cc.Invoke(ctx, "/proto.Moneytree/PlacePair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneytreeClient) GetOpenOrders(ctx context.Context, in *NullRequest, opts ...grpc.CallOption) (*PairCollection, error) {
	out := new(PairCollection)
	err := c.cc.Invoke(ctx, "/proto.Moneytree/GetOpenOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoneytreeServer is the server API for Moneytree service.
// All implementations must embed UnimplementedMoneytreeServer
// for forward compatibility
type MoneytreeServer interface {
	// Places an order pair in the system using the current price as the starting point.
	PlacePair(context.Context, *PlacePairRequest) (*PlacePairResponse, error)
	GetOpenOrders(context.Context, *NullRequest) (*PairCollection, error)
	mustEmbedUnimplementedMoneytreeServer()
}

// UnimplementedMoneytreeServer must be embedded to have forward compatible implementations.
type UnimplementedMoneytreeServer struct {
}

func (UnimplementedMoneytreeServer) PlacePair(context.Context, *PlacePairRequest) (*PlacePairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlacePair not implemented")
}
func (UnimplementedMoneytreeServer) GetOpenOrders(context.Context, *NullRequest) (*PairCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpenOrders not implemented")
}
func (UnimplementedMoneytreeServer) mustEmbedUnimplementedMoneytreeServer() {}

// UnsafeMoneytreeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoneytreeServer will
// result in compilation errors.
type UnsafeMoneytreeServer interface {
	mustEmbedUnimplementedMoneytreeServer()
}

func RegisterMoneytreeServer(s grpc.ServiceRegistrar, srv MoneytreeServer) {
	s.RegisterService(&_Moneytree_serviceDesc, srv)
}

func _Moneytree_PlacePair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlacePairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneytreeServer).PlacePair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Moneytree/PlacePair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneytreeServer).PlacePair(ctx, req.(*PlacePairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moneytree_GetOpenOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneytreeServer).GetOpenOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Moneytree/GetOpenOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneytreeServer).GetOpenOrders(ctx, req.(*NullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Moneytree_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Moneytree",
	HandlerType: (*MoneytreeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlacePair",
			Handler:    _Moneytree_PlacePair_Handler,
		},
		{
			MethodName: "GetOpenOrders",
			Handler:    _Moneytree_GetOpenOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/moneytree.proto",
}
